#' help_panel UI Function
#'
#' @description An interactive tutorial and help panel detailing the ScIGMA workflow.
#'
#' @param id,input,output,session Internal parameters for {shiny}.
#'
#' @noRd
#'
#' @importFrom shiny NS tagList icon markdown div h4 h5 hr fluidRow column
#' @importFrom bslib card card_header card_body navset_card_underline nav_panel accordion accordion_panel
mod_help_panel_ui <- function(id) {
    ns <- NS(id)
    shiny::tagList(
        bslib::navset_card_underline(
            id = ns("help_tabs"),
            # title = shiny::tagList(shiny::icon("life-ring"), "ScIGMA Tutorial & Guidelines"),

            # --- TAB 1: PREPROCESSING ---
            bslib::nav_panel(
                title = "1. Input & Preprocessing",
                icon = shiny::icon("file-import"),
                bslib::card_body(
                    shiny::markdown("
          ### Data Loading & Quality Control
          The workflow begins by processing multiplexed single-cell `.h5` files generated by the Mission Bio Tapestri pipeline. You must select the appropriate assay type depending on your experimental setup: **DNA only** or **DNA & Protein**.

          ### Technical Variant & Cell Filtering Parameters
          To resolve high-quality somatic variants, ScIGMA filters the raw data matrices across two key thresholds:
          "),
                    shiny::fluidRow(
                        shiny::column(6,
                                      shiny::div(
                                          class = "card border-secondary mb-3",
                                          shiny::div(class = "card-header bg-light font-weight-bold", "Cell Completeness Threshold (min.cell.pt)"),
                                          shiny::div(
                                              class = "card-body text-dark",
                                              shiny::markdown("
                  * **Definition:** Minimum percentage of cells that must possess a valid, non-missing variant call genotype (`GT = 0, 1, or 2`) for a specific variant to pass the filter.
                  * **Optimization Guideline:** If your target variant is located within an amplicon characterized by high GC-content or secondary structures, PCR amplification efficiency drops dramatically, causing extensive missing calls. In these scenarios, **decrease this threshold to 30% or 40%** to avoid discarding valuable loci.
                  ")
                                          )
                                      )
                        ),
                        shiny::column(6,
                                      shiny::div(
                                          class = "card border-secondary mb-3",
                                          shiny::div(class = "card-header bg-light font-weight-bold", "Mutation Prevalence Threshold (min.mut.cell.pt)"),
                                          shiny::div(
                                              class = "card-body text-dark",
                                              shiny::markdown("
                  * **Definition:** Minimum percentage of cells that must display a mutated genotype (`GT = 1 or 2`, heterozygous or homozygous mutant) for that variant to be retained.
                  * **Optimization Guideline:** When tracking rare subclones, low-frequency ancestral mutations, or minimal residual disease (MRD) variants, **lower this threshold** to prevent the pipeline from filtering out critical subclonal mutations.
                  ")
                                          )
                                      )
                        )
                    ),
                    shiny::markdown("
          *Note: This execution takes several seconds as it filters out low-coverage elements, normalizes surface proteomic counts (if applicable), and builds the initial PCA space.*
          "),
                    shiny::div(
                        style = "text-align: center; margin: 20px 0;",
                        class = "alert alert-secondary",
                        shiny::icon("image"), " Placeholder: Preprocessing & Data Loading Layout (www/help_preprocessing.png)"
                    )
                )
            ),

            # --- TAB 2: DNA & COMPASS ---
            bslib::nav_panel(
                title = "2. DNA Selection & COMPASS",
                icon = shiny::icon("dna"),
                bslib::card_body(
                    shiny::markdown("
          ### Clonal Architecture Resolution
          Navigate to the **SNV** panel to execute single-cell genomic dissection through a three-step cycle:

          1. **Select DNA Variants:** Isolate reliable, informative mutations from the server-side datatable.
          2. **Heatmap Visualization:** Inspect high-resolution single-cell mutational profiles across all cells.
          3. **Clone Renaming:** Dynamically rename detected single-cell genotypes to match standard clinical nomenclature.

          ### Probabilistic Phylogeny with COMPASS
          Once your target somatic variants are locked, the **COMPASS** tab initializes.
          "),
                    shiny::div(
                        class = "alert alert-info",
                        shiny::markdown("
            **COMPASS** (*Copy number and Mutation Phylogeny from Amplicon Single-cell Sequencing*) is a Bayesian probabilistic framework designed to model the technical artifacts inherent to targeted single-cell DNA-seq. It leverages a Markov Chain Monte Carlo (MCMC) sampler to jointly resolve **Allelic Dropout (ADO)** events and **cell doublets**, inferring high-resolution phylogenetic trees.
            ")
                    ),
                    shiny::div(
                        style = "text-align: center; margin: 20px 0;",
                        class = "alert alert-secondary",
                        shiny::icon("image"), " Placeholder: COMPASS MCMC Phylogenetic Tree (www/help_compass_tree.png)"
                    )
                )
            ),

            # --- TAB 3: CNV ---
            bslib::nav_panel(
                title = "3. CNV Analysis",
                icon = shiny::icon("chart-line"),
                bslib::card_body(
                    shiny::markdown("
          ### Chromosomal Copy Number Architecture
          The **CNV** module reconstructs single-cell ploidy variations from amplicon sequencing read-depth distributions.

          * **Amplicon Filtering:** Establishes read-depth quality controls per amplicon to filter out noisy probes.
          * **Multi-Scale Inferences:** Generates polished single-cell copy number alterations figures grouped by:
            * **Target Genes:** To detect focal amplifications or micro-deletions.
            * **Chromosomes:** To visualize large-scale aneuploidies, trisomies, or monosomies.
          * **Visualization Engine:** Provides toggles between global clustered Heatmaps and interactive single-cell profile Lineplots.
          "),
                    shiny::div(
                        style = "text-align: center; margin: 20px 0;",
                        class = "alert alert-secondary",
                        shiny::icon("image"), " Placeholder: Genomic CNV Profile Lineplot (www/help_cnv_profiles.png)"
                    )
                )
            ),

            # --- TAB 4: PROTEINS ---
            bslib::nav_panel(
                title = "4. Protein Surface Markers",
                icon = shiny::icon("id-card"),
                bslib::card_body(
                    bslib::accordion(
                        id = ns("protein_help_accordion"),
                        multiple = FALSE,

                        bslib::accordion_panel(
                            title = "Descriptive Expression & Manual Gating",
                            icon = shiny::icon("chart-bar"),
                            shiny::markdown("
              * **Ridge Plots & Barplots:** Assess the continuous expression landscape and distribution of cell-surface markers across your cohort.
              * **AbSeq Gating:** Replicate classic flow cytometry gating hierarchies natively in single-cell multi-omics. Interactively draw polygons on 2D antibody-oligo plots to isolate pure immunophenotypic subpopulations.
              ")
                        ),

                        bslib::accordion_panel(
                            title = "UMAP Dimensionality Reduction & Topology Rules",
                            icon = shiny::icon("project-diagram"),
                            shiny::markdown("
              Configure non-linear dimensionality reduction by tweaking two fundamental hyperparameters:

              * **Number of Neighbors:** Controls the balance between local and global structure preservation. *Higher values* capture broad macroscopic manifolds; *lower values* preserve localized subpopulation niches.
              * **Minimum Distance:** Determines how tightly cells are packed together in the low-dimensional embedding space.

              ### Mathematical Evaluation Metrics
              To ensure publication-grade rigor, ScIGMA evaluates every computed UMAP using a dedicated spider-plot displaying three metrics:
              1. **Trustworthiness:** Measures the degree to which high-dimensional nearest neighbors are preserved in the 2D projection (prevents false clusters).
              2. **Continuity:** Quantifies how well local structural connections are maintained (prevents cluster fracturing).
              3. **Global Spearman Correlation:** Computes the correlation of all-to-all pairwise distances between the high-dimensional normalized space and the low-dimensional embedding.
              ")
                        ),

                        bslib::accordion_panel(
                            title = "Interactive Proteomic Accordions Layout",
                            icon = shiny::icon("layer-group"),
                            shiny::markdown("
              * **Markers Expression Accordion:** *Left Panel:* Select antibody targets. *Right Panel:* Generates a split grid overlaying continuous normalized expression values across the UMAP.
              * **AbSeq Gating Accordion:** *Left Panel:* Select active manual gates. *Right Panel:* Maps selected gated populations as binary layers onto the UMAP coordinates.
              * **Unsupervised Clustering Accordion:** *Left Panel:* Fine-tune the Louvain/Leiden resolution parameter (higher values yield a larger number of distinct phenotypic clusters). *Right Panel:* Displays categorical cluster color assignments.
              ")
                        )
                    ),
                    shiny::div(
                        style = "text-align: center; margin: 20px 0;",
                        class = "alert alert-secondary",
                        shiny::icon("image"), " Placeholder: Protein UMAP Modeler Dashboard (www/help_protein_umap.png)"
                    )
                )
            ),

            # --- TAB 5: MULTI-OMICS ---
            bslib::nav_panel(
                title = "5. Multi-omics Integration",
                icon = shiny::icon("network-wired"),
                bslib::card_body(
                    shiny::markdown("
          ### Joint Genotype-to-Phenotype Mapping
          The final synthesis cockpit bridges somatic mutations directly with phenotypic landscapes across three specialized sub-modules:
          "),

                    bslib::accordion(
                        id = ns("multiomics_help_accordion"),
                        multiple = FALSE,

                        bslib::accordion_panel(
                            title = "Protein UMAP x SNV Mapping",
                            icon = shiny::icon("map-marked-alt"),
                            shiny::markdown("
              * **DNA Clones Accordion:** Projects fully resolved phylogenetic clones directly as discrete color overlays onto the proteomic UMAP coordinates.
              * **DNA Variants Accordion:** *Left Panel:* Select specific mutations. *Right Panel:* Visualizes categorical single-cell genotypes (`WT`, `HET`, `HOM`, `Missing`) across the UMAP space to trace mutational penetrance.
              ")
                        ),

                        bslib::accordion_panel(
                            title = "UMAP Unsupervised Clusters x SNV Mapping",
                            icon = shiny::icon("chart-pie"),
                            shiny::markdown("
              * **DNA Clones Accordion:** Generates stacked barplots showing the exact compositional distribution of phylogenetic clones across each unsupervised proteomic cluster.
              * **DNA Variants Accordion:** Renders stacked barplots displaying the frequency distribution of individual genotypes (`WT`, `HET`, `HOM`, `Missing/ADO`) across cell-surface marker clusters.
              ")
                        ),

                        bslib::accordion_panel(
                            title = "AbSeq Gating x SNV Mapping",
                            icon = shiny::icon("filter"),
                            shiny::markdown("
              * **Interface Strategy:** *Left Panel:* Select manually gated cell populations. *Right Panel:* Displays rigorous stacked barplots breaking down the exact mutational or subclonal composition contained within that specific phenotypic gate. Allows direct validation of immunophenotypic markers for targeted cell sorting.
              ")
                        )
                    ),
                    shiny::div(
                        style = "text-align: center; margin: 20px 0;",
                        class = "alert alert-secondary",
                        shiny::icon("image"), " Placeholder: Multi-omics Pheno-Genotypic Barplot (www/help_multiomics_integ.png)"
                    )
                )
            )
        )
    )
}

#' help_panel Server Functions
#'
#' @noRd
mod_help_panel_server <- function(id, ScIGMA_data){
    moduleServer(id, function(input, output, session){
        ns <- session$ns
        # Static documentation rendering, reactive state tracking is handled by UI components.
    })
}

## To be copied in the UI
# mod_help_panel_ui("help_panel_1")

## To be copied in the server
# mod_help_panel_server("help_panel_1", ScIGMA_data)
