#' help_panel UI Function
#'
#' @description A shiny Module to display documentation and user tutorials.
#'
#' @param id,input,output,session Internal parameters for {shiny}.
#'
#' @noRd
#'
#' @importFrom shiny NS tagList icon markdown div
#' @importFrom bslib card card_header card_body accordion accordion_panel
mod_help_panel_ui <- function(id) {
    ns <- NS(id)
    shiny::tagList(
        bslib::card(
            bslib::card_header(
                shiny::icon("circle-info"),
                "ScIGMA User Guide & Documentation",
                class = "bg-primary text-white"
            ),
            bslib::card_body(
                bslib::accordion(
                    id = ns("help_accordion"),
                    multiple = FALSE,
                    bslib::accordion_panel(
                        title = "1. Data Input & Preprocessing",
                        icon = shiny::icon("file-import"),
                        shiny::markdown("
            ### Loading your Mission-Bio Tapestry Dataset
            Upload your multi-omics `.h5` file generated by the pipeline.

            * **DNA Only:** For single-cell genomic copy number and SNV analysis.
            * **DNA & Protein:** Joint genomic and cell-surface proteomic profiling.
            "),
                        shiny::div(
                            style = "text-align: center; margin: 15px 0;",
                            class = "alert alert-secondary",
                            shiny::icon("image"),
                            " Placeholder: Upload Panel Layout (www/help_upload.png)"
                        )
                    ),
                    bslib::accordion_panel(
                        title = "2. DNA Variant Selection & COMPASS",
                        icon = shiny::icon("dna"),
                        shiny::markdown("
            ### Filtering & Phylogeny Reconstruction
            Navigate to the **DNA** tab to isolate high-quality variants.

            1. Filter amplicons based on read depth and completeness.
            2. Run the **COMPASS** MCMC algorithm to resolve missing data (ADOs).
            3. Track subclonal architecture using the inferred phylogenetic tree.
            "),
                        shiny::div(
                            style = "text-align: center; margin: 15px 0;",
                            class = "alert alert-secondary",
                            shiny::icon("image"),
                            " Placeholder: COMPASS Phylogenetic Tree (www/help_dna.png)"
                        )
                    ),
                    bslib::accordion_panel(
                        title = "3. Copy Number Variation (CNV)",
                        icon = shiny::icon("chart-line"),
                        shiny::markdown("
            ### Clonal Ploidy Profiles
            The **CNV** module computes single-cell copy number variations:

            * Select a **Diploid Clone** to anchor baseline ploidy levels.
            * Select target genomic loci by **Chromosomes** or **Genes**.
            * Visualize large-scale events via Heatmaps or interactive Lineplots.
            "),
                        shiny::div(
                            style = "text-align: center; margin: 15px 0;",
                            class = "alert alert-secondary",
                            shiny::icon("image"),
                            " Placeholder: CNV Heatmap Profiles (www/help_cnv.png)"
                        )
                    ),
                    bslib::accordion_panel(
                        title = "4. Protein Expression & Manual Gating",
                        icon = shiny::icon("id-card"),
                        shiny::markdown("
            ### Single-Cell Proteomics Cockpit
            For joint multi-omics assays, inspect cell-surface marker phenotypes:

            * Evaluate marker distributions using Ridge plots and Barplots.
            * Apply manual **Biplot Gating** to dissect target populations.
            * Compute **UMAP** topology and perform unsupervised clustering.
            "),
                        shiny::div(
                            style = "text-align: center; margin: 15px 0;",
                            class = "alert alert-secondary",
                            shiny::icon("image"),
                            " Placeholder: Protein Gating Cockpit (www/help_protein.png)"
                        )
                    ),
                    bslib::accordion_panel(
                        title = "5. Multi-omics Integration",
                        icon = shiny::icon("network-wired"),
                        shiny::markdown("
            ### Joint Pheno-Genotypic Mapping
            Correlate somatic genotypes directly with phenotypic landscapes:

            * Track variant frequency distribution across protein clusters.
            * Overlay DNA clone paths onto phenotypic UMAP projections.
            * Assess mutational status inside manually gated subpopulations.
            "),
                        shiny::div(
                            style = "text-align: center; margin: 15px 0;",
                            class = "alert alert-secondary",
                            shiny::icon("image"),
                            " Placeholder: Multi-omics Mapping (www/help_multiomics.png)"
                        )
                    )
                )
            )
        )
    )
}

#' help_panel Server Functions
#'
#' @noRd
mod_help_panel_server <- function(id, ScIGMA_data){
    moduleServer(id, function(input, output, session){
        ns <- session$ns
        # Server logic can remain unpopulated for static documentation rendering.
    })
}

## To be copied in the UI
# mod_help_panel_ui("help_panel_1")

## To be copied in the server
# mod_help_panel_server("help_panel_1", ScIGMA_data)
