#' help_panel UI Function
#'
#' @description An interactive tutorial and help panel detailing the ScIGMA workflow.
#'
#' @param id,input,output,session Internal parameters for {shiny}.
#'
#' @noRd
#'
#' @importFrom shiny NS tagList icon markdown div h4 h5 hr fluidRow column
#' @importFrom bslib card card_header card_body navset_card_underline nav_panel accordion accordion_panel
mod_help_panel_ui <- function(id) {
    ns <- NS(id)
    shiny::tagList(
        bslib::navset_card_underline(
            id = ns("help_tabs"),
            # title = shiny::tagList(shiny::icon("life-ring"), "ScIGMA Tutorial & Guidelines"),
            
            # --- TAB 1: PREPROCESSING ---
            bslib::nav_panel(
                title = "1. Input & Preprocessing",
                icon = shiny::icon("file-import"),
                bslib::card_body(
                    shiny::markdown("
          ### Data Loading & Quality Control
          The workflow begins by processing multiplexed single-cell `.h5` files generated by the Mission Bio Tapestri pipeline. You must select the appropriate assay type depending on your experimental setup: **DNA only** or **DNA & Protein**.
                    
          ### Technical Variant & Cell Filtering Parameters
          To resolve high-quality somatic variants, ScIGMA filters the raw data matrices across two key thresholds:
          "),
                    shiny::fluidRow(
                        shiny::column(6,
                            shiny::div(
                                class = "card border-secondary mb-3",
                                shiny::div(class = "card-header bg-light font-weight-bold", "Cell Completeness Threshold (min.cell.pt)"),
                                shiny::div(
                                    class = "card-body text-dark",
                                    shiny::markdown("
                  * **Definition:** Minimum percentage of cells that must possess a valid, non-missing variant call genotype (`GT = 0, 1, or 2`) for a specific variant to pass the filter.
                  * **Optimization Guideline:** If your target variant is located within an amplicon characterized by high GC-content or secondary structures, PCR amplification efficiency drops dramatically, causing extensive missing calls. In these scenarios, **decrease this threshold to 30% or 40%** to avoid discarding valuable loci.
                  ")
                                )
                            )
                        ),
                        shiny::column(6,
                            shiny::div(
                                class = "card border-secondary mb-3",
                                shiny::div(class = "card-header bg-light font-weight-bold", "Mutation Prevalence Threshold (min.mut.cell.pt)"),
                                shiny::div(
                                    class = "card-body text-dark",
                                    shiny::markdown("
                  * **Definition:** Minimum percentage of cells that must display a mutated genotype (`GT = 1 or 2`, heterozygous or homozygous mutant) for that variant to be retained.
                  * **Optimization Guideline:** When tracking rare subclones, low-frequency ancestral mutations, or minimal residual disease (MRD) variants, **lower this threshold** to prevent the pipeline from filtering out critical subclonal mutations.
                  ")
                                )
                            )
                        )
                    ),
                    shiny::markdown("
          *Note: This execution takes several seconds as it filters out low-coverage elements, normalizes surface proteomic counts (if applicable), and builds the initial PCA space.*
          "),
                    tags$figure(
                        style = "display: inline-block; text-align: center;",
                        
                        tags$img(src = "www/img/1_Load_and_process.png", width = "90%"),
                        
                        tags$figcaption(
                            style = "margin-top: 8px; color: #555555;", 
                            tags$em("Fig. 1: Overview of the 'Load and Process' module.")
                        )
                        
                    )
                )
            ),
            
            # --- TAB 2: DNA & COMPASS ---
            bslib::nav_panel(
                title = "2. DNA Selection & COMPASS",
                icon = shiny::icon("dna"),
                bslib::card_body(
                    shiny::markdown("
          ### Clonal Architecture Resolution
          Navigate to the **SNV** panel to execute single-cell genomic dissection through a three-step cycle:
                    
          1. **Select DNA Variants:** Isolate reliable, informative mutations from the server-side datatable.
          2. **Heatmap Visualization:** Inspect high-resolution single-cell mutational profiles across all cells.
          3. **Clone Renaming:** Dynamically rename detected single-cell genotypes to match standard clinical nomenclature.
          "),
                    
                    tags$figure(
                        style = "display: inline-block; text-align: center;",
                        
                        tags$img(src = "www/img/2_SNV_Descriptive_heatmap.png", width = "90%"),
                        
                        tags$figcaption(
                            style = "margin-top: 8px; color: #555555;", 
                            tags$em("Fig. 2: SNV panel - DNA variant selection and visualization.")
                        )
                        
                    ),
                    
                    shiny::markdown(
                        "### Probabilistic Phylogeny with COMPASS
                        Once your target somatic variants are locked, the **COMPASS** tab initializes."
                    ),
                    shiny::div(
                        class = "alert alert-info",
                        shiny::markdown(
                            "**COMPASS** (*Copy number and Mutation Phylogeny from Amplicon Single-cell Sequencing*) is 
                            a Bayesian probabilistic framework designed to model the technical artifacts inherent to 
                            targeted single-cell DNA-seq. It leverages a Markov Chain Monte Carlo (MCMC) sampler to 
                            jointly resolve **Allelic Dropout (ADO)** events and **cell doublets**, inferring 
                            high-resolution phylogenetic trees."
                        )
                    ),
                    
                    tags$figure(
                        style = "display: inline-block; text-align: center;",
                        
                        tags$img(src = "www/img/3_SNV_COMPASS.png", width = "90%"),
                        
                        tags$figcaption(
                            style = "margin-top: 8px; color: #555555;", 
                            tags$em("Fig. 3: SNV panel - COMPASS processing and phylogenetic tree.")
                        )
                        
                    )
                )
            ),
            
            # --- TAB 3: CNV ---
            bslib::nav_panel(
                title = "3. CNV Analysis",
                icon = shiny::icon("chart-line"),
                bslib::card_body(
                    shiny::markdown("
                ### Chromosomal Copy Number Architecture
                The **CNV** module reconstructs single-cell ploidy variations 
                from amplicon sequencing read-depth distributions.
                
                * **Amplicon Filtering:** Establishes read-depth quality controls per amplicon to filter out noisy probes.
                * **Multi-Scale Inferences:** Generates polished single-cell copy number alterations figures grouped by:
                    * **Target Genes:** To detect focal amplifications or micro-deletions.
                * **Chromosomes:** To visualize large-scale aneuploidies, trisomies, or monosomies.
                * **Visualization Engine:** Provides toggles between global clustered Heatmaps and interactive 
                single-cell profile Lineplots."
                ),
                shiny::fluidRow(
                    shiny::column(6, 
                        tags$figure(
                            style = "display: inline-block; text-align: center;",
                            
                            tags$img(src = "www/img/4_CNV_heatmap.png", width = "90%"),
                            
                            tags$figcaption(
                                style = "margin-top: 8px; color: #555555;", 
                                tags$em("Fig. 4: CNV panel - Amplicon filtering and heatmap.")
                            )
                            
                        )
                    ),
                    shiny::column(6, 
                        tags$figure(
                            style = "display: inline-block; text-align: center;",
                            
                            tags$img(src = "www/img/5_CNV_lineplot.png", width = "90%"),
                            
                            tags$figcaption(
                                style = "margin-top: 8px; color: #555555;", 
                                tags$em("Fig. 5: CNV panel - amplicon filtering and line plots.")
                            )
                        )
                    )
                )
            )
        ),
        
        # --- TAB 4: PROTEINS ---
        bslib::nav_panel(
            title = "4. Immunophenotype analysis",
            icon = shiny::icon("id-card"),
            bslib::card_body(
                bslib::accordion(
                    id = ns("protein_help_accordion"),
                    multiple = FALSE,
                    
                    bslib::accordion_panel(
                        title = "Descriptive Expression & Manual Gating",
                        icon = shiny::icon("chart-bar"),
                        shiny::markdown("
              * **Ridge Plots & Barplots:** Assess the continuous expression landscape and distribution of cell-surface markers across your cohort.
              * **Immunophenotype Gating:** Replicate classic flow cytometry gating hierarchies natively in single-cell multi-omics. Interactively draw polygons on 2D antibody-oligo plots to isolate pure immunophenotypic subpopulations.
              "),
                        tags$figure(
                            style = "display: inline-block; text-align: center;",
                            
                            tags$img(src = "www/img/6_abseq_ridge_barplot.png", width = "90%"),
                            
                            tags$figcaption(
                                style = "margin-top: 8px; color: #555555;", 
                                tags$em("Fig. 6: Immunophenotype tab - Descriptive panel: ridge plots and barplots of protein abundances.")
                            )
                        )
                    ),
                    
                    bslib::accordion_panel(
                        title = "UMAP Dimensionality Reduction & Topology Rules",
                        icon = shiny::icon("project-diagram"),
                        shiny::markdown("
              Configure non-linear dimensionality reduction by tweaking two fundamental hyperparameters:
                            
              * **Number of Neighbors:** Controls the balance between local and global structure preservation. *Higher values* capture broad macroscopic manifolds; *lower values* preserve localized subpopulation niches.
              * **Minimum Distance:** Determines how tightly cells are packed together in the low-dimensional embedding space.
                            
              ### Mathematical Evaluation Metrics
              To ensure publication-grade rigor, ScIGMA evaluates every computed UMAP using a dedicated spider-plot displaying three metrics:
              1. **Trustworthiness:** Measures the degree to which high-dimensional nearest neighbors are preserved in the 2D projection (prevents false clusters).
              2. **Continuity:** Quantifies how well local structural connections are maintained (prevents cluster fracturing).
              3. **Global Spearman Correlation:** Computes the correlation of all-to-all pairwise distances between the high-dimensional normalized space and the low-dimensional embedding.
              "),
                        tags$figure(
                            style = "display: inline-block; text-align: center;",
                            
                            tags$img(src = "www/img/7_abseq_biplot_DNAproj.png", width = "90%"),
                            
                            tags$figcaption(
                                style = "margin-top: 8px; color: #555555;", 
                                tags$em("Fig. 7: Immunophenotype analysis - FCM-like gating and projection of DNA clones.")
                            )
                        )
                    ),
                    
                    bslib::accordion_panel(
                        title = "Interactive Proteomic Accordions Layout",
                        icon = shiny::icon("layer-group"),
                        shiny::markdown("
              * **Markers Expression Accordion:** *Left Panel:* Select antibody targets. *Right Panel:* Generates a split grid overlaying continuous normalized expression values across the UMAP.
              * **Immunophenotype Gating Accordion:** *Left Panel:* Select active manual gates. *Right Panel:* Maps selected gated populations as binary layers onto the UMAP coordinates.
              * **Unsupervised Clustering Accordion:** *Left Panel:* Fine-tune the Louvain/Leiden resolution parameter (higher values yield a larger number of distinct phenotypic clusters). *Right Panel:* Displays categorical cluster color assignments.
              "),
                        shiny::fluidRow(
                            shiny::column(6, 
                                tags$figure(
                                    style = "display: inline-block; text-align: center;",
                                    
                                    tags$img(src = "www/img/8_abseq_UMAP_1.png", width = "90%"),
                                    
                                    tags$figcaption(
                                        style = "margin-top: 8px; color: #555555;", 
                                        tags$em("Fig. 8: Immunophenotype analysis - UMAP projection and protein marker expression.")
                                    )
                                    
                                )
                            ),
                            shiny::column(6, 
                                tags$figure(
                                    style = "display: inline-block; text-align: center;",
                                    
                                    tags$img(src = "www/img/9_abseq_UMAP_2.png", width = "90%"),
                                    
                                    tags$figcaption(
                                        style = "margin-top: 8px; color: #555555;", 
                                        tags$em("Fig. 9: Immunophenotype subpopulation projection and unsupervised clustering on UMAP.")
                                    )
                                )
                            )
                        )
                    )
                )
            )
        ),
        
        # --- TAB 5: MULTI-OMICS ---
        bslib::nav_panel(
            title = "5. Multi-omics Integration",
            icon = shiny::icon("network-wired"),
            bslib::card_body(
                shiny::markdown("
          ### Joint Genotype-to-Phenotype Mapping
          The final synthesis cockpit bridges somatic mutations directly with phenotypic landscapes across three specialized sub-modules:
          "),
                
                bslib::accordion(
                    id = ns("multiomics_help_accordion"),
                    multiple = FALSE,
                    
                    bslib::accordion_panel(
                        title = "Protein UMAP x SNV Mapping",
                        icon = shiny::icon("map-marked-alt"),
                        shiny::markdown("
              * **DNA Clones Accordion:** Projects fully resolved phylogenetic clones directly as discrete color overlays onto the proteomic UMAP coordinates.
              * **DNA Variants Accordion:** *Left Panel:* Select specific mutations. *Right Panel:* Visualizes categorical single-cell genotypes (`WT`, `HET`, `HOM`, `Missing`) across the UMAP space to trace mutational penetrance.
              "),
                        tags$figure(
                            style = "display: inline-block; text-align: center;",
                            
                            tags$img(src = "www/img/10_multiomics_umap_snv.png", width = "90%"),
                            
                            tags$figcaption(
                                style = "margin-top: 8px; color: #555555;", 
                                tags$em("Fig. 10: Multi-omics panel - DNA clone and variant genotypes projected on protein-based UMAP.")
                            )
                        )
                    ),
                    
                    bslib::accordion_panel(
                        title = "UMAP Unsupervised Clusters x SNV Mapping",
                        icon = shiny::icon("chart-pie"),
                        shiny::markdown("
              * **DNA Clones Accordion:** Generates stacked barplots showing the exact compositional distribution of phylogenetic clones across each unsupervised proteomic cluster.
              * **DNA Variants Accordion:** Renders stacked barplots displaying the frequency distribution of individual genotypes (`WT`, `HET`, `HOM`, `Missing/ADO`) across cell-surface marker clusters.
              "),
                        tags$figure(
                            style = "display: inline-block; text-align: center;",
                            
                            tags$img(src = "www/img/11_multiomics_cluster_snv.png", width = "90%"),
                            
                            tags$figcaption(
                                style = "margin-top: 8px; color: #555555;", 
                                tags$em("Fig. 11: Multi-omics panel - DNA clone and variant genotype distribution across unsupervised clusters.")
                            )
                        )
                    ),
                    
                    bslib::accordion_panel(
                        title = "Immunophenotype Gating x SNV Mapping",
                        icon = shiny::icon("filter"),
                        shiny::markdown("
              * **Interface Strategy:** *Left Panel:* Select manually gated cell populations. *Right Panel:* Displays rigorous stacked barplots breaking down the exact mutational or subclonal composition contained within that specific phenotypic gate. Allows direct validation of immunophenotypic markers for targeted cell sorting.
              "),
                        tags$figure(
                            style = "display: inline-block; text-align: center;",
                            
                            tags$img(src = "www/img/12_multiomics_abSeq_SNV.png", width = "90%"),
                            
                            tags$figcaption(
                                style = "margin-top: 8px; color: #555555;", 
                                tags$em("Fig. 12: Multi-omics panel - Variant genotype distribution across Immunophenotype subpopulations.")
                            )
                        )
                    )
                )
            )
        ),
        
        # --- TAB 6: DATA EXPORT ---
        bslib::nav_panel(
            title = "6. Data Export",
            icon = shiny::icon("download"),
            bslib::card_body(
                shiny::markdown("
          ### Exporting Results & Analysis
          ScIGMA provides comprehensive export capabilities allowing you to download processed datasets and generated figures for downstream applications and publication.
          
          * **Processed Data:** Export your filtered and normalized single-cell matrices, including variant calls and proteomic counts, in standard tabular formats.
          * **High-Resolution Figures:** Download publication-ready plots (UMAP, heatmaps, phylogenies) directly from their respective modules.
          * **Clonal Assignments:** Retrieve the exact cell-to-clone mapping inferred by COMPASS and the corresponding single-cell genotype matrices.
          "),
                tags$figure(
                    style = "display: inline-block; text-align: center;",
                    
                    tags$img(src = "www/img/13_download.png", width = "90%"),
                    
                    tags$figcaption(
                        style = "margin-top: 8px; color: #555555;", 
                        tags$em("Fig. 13: Data export options.")
                    )
                )
            )
        )
    )
)
}

#' help_panel Server Functions
#'
#' @noRd
mod_help_panel_server <- function(id, ScIGMA_data){
    moduleServer(id, function(input, output, session){
        ns <- session$ns
        # Static documentation rendering, reactive state tracking is handled by UI components.
    })
}

## To be copied in the UI
# mod_help_panel_ui("help_panel_1")

## To be copied in the server
# mod_help_panel_server("help_panel_1", ScIGMA_data)
