# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_compass_inference_cpp <- function(ref_counts, alt_counts, genotypes, locus_region_mapping, region_counts, locus_names, locus_chromosomes, region_names, region_chromosomes, cell_names, output_prefix, n_chains = 4L, chain_length = 5000L, use_cna = TRUE, sex = "female") {
    .Call(`_ScIGMA_run_compass_inference_cpp`, ref_counts, alt_counts, genotypes, locus_region_mapping, region_counts, locus_names, locus_chromosomes, region_names, region_chromosomes, cell_names, output_prefix, n_chains, chain_length, use_cna, sex)
}

